//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 04:28:33 PM BRT 
//


package br.com.guava.documento.fiscal.xsd.one.manutencao;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for TLeitura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TLeitura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any/>
 *         &lt;element name="infMDFe" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="chMDFe" type="{http://www.portalfiscal.inf.br/one}TChMDFe"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infCompl">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tpLeitura">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/one}TString">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;choice minOccurs="0">
 *                     &lt;element name="xSLD" type="{http://www.portalfiscal.inf.br/one}TString"/>
 *                     &lt;element name="xOCR" type="{http://www.portalfiscal.inf.br/one}TString"/>
 *                   &lt;/choice>
 *                   &lt;element name="latitude" type="{http://www.portalfiscal.inf.br/one}TLatitude"/>
 *                   &lt;element name="longitude" type="{http://www.portalfiscal.inf.br/one}TLongitude"/>
 *                   &lt;element name="placa" type="{http://www.portalfiscal.inf.br/one}TPlaca"/>
 *                   &lt;element name="tpSentido">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="E"/>
 *                         &lt;enumeration value="S"/>
 *                         &lt;enumeration value="I"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NSULeitura" type="{http://www.portalfiscal.inf.br/one}TNSU"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="NSU" use="required" type="{http://www.portalfiscal.inf.br/one}TNSU" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLeitura", propOrder = {
    "any",
    "infMDFe",
    "infCompl"
})
public class TLeitura {

    @XmlAnyElement
    protected Element any;
    protected List<TLeitura.InfMDFe> infMDFe;
    @XmlElement(required = true)
    protected TLeitura.InfCompl infCompl;
    @XmlAttribute(name = "NSU", required = true)
    protected String nsu;

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setAny(Element value) {
        this.any = value;
    }

    /**
     * Gets the value of the infMDFe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infMDFe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfMDFe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLeitura.InfMDFe }
     * 
     * 
     */
    public List<TLeitura.InfMDFe> getInfMDFe() {
        if (infMDFe == null) {
            infMDFe = new ArrayList<TLeitura.InfMDFe>();
        }
        return this.infMDFe;
    }

    /**
     * Gets the value of the infCompl property.
     * 
     * @return
     *     possible object is
     *     {@link TLeitura.InfCompl }
     *     
     */
    public TLeitura.InfCompl getInfCompl() {
        return infCompl;
    }

    /**
     * Sets the value of the infCompl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLeitura.InfCompl }
     *     
     */
    public void setInfCompl(TLeitura.InfCompl value) {
        this.infCompl = value;
    }

    /**
     * Gets the value of the nsu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNSU() {
        return nsu;
    }

    /**
     * Sets the value of the nsu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNSU(String value) {
        this.nsu = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tpLeitura">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/one}TString">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;choice minOccurs="0">
     *           &lt;element name="xSLD" type="{http://www.portalfiscal.inf.br/one}TString"/>
     *           &lt;element name="xOCR" type="{http://www.portalfiscal.inf.br/one}TString"/>
     *         &lt;/choice>
     *         &lt;element name="latitude" type="{http://www.portalfiscal.inf.br/one}TLatitude"/>
     *         &lt;element name="longitude" type="{http://www.portalfiscal.inf.br/one}TLongitude"/>
     *         &lt;element name="placa" type="{http://www.portalfiscal.inf.br/one}TPlaca"/>
     *         &lt;element name="tpSentido">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="S"/>
     *               &lt;enumeration value="I"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="NSULeitura" type="{http://www.portalfiscal.inf.br/one}TNSU"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpLeitura",
        "xsld",
        "xocr",
        "latitude",
        "longitude",
        "placa",
        "tpSentido",
        "nsuLeitura"
    })
    public static class InfCompl {

        @XmlElement(required = true)
        protected String tpLeitura;
        @XmlElement(name = "xSLD")
        protected String xsld;
        @XmlElement(name = "xOCR")
        protected String xocr;
        @XmlElement(required = true)
        protected String latitude;
        @XmlElement(required = true)
        protected String longitude;
        @XmlElement(required = true)
        protected String placa;
        @XmlElement(required = true)
        protected String tpSentido;
        @XmlElement(name = "NSULeitura", required = true)
        protected String nsuLeitura;

        /**
         * Gets the value of the tpLeitura property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpLeitura() {
            return tpLeitura;
        }

        /**
         * Sets the value of the tpLeitura property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpLeitura(String value) {
            this.tpLeitura = value;
        }

        /**
         * Gets the value of the xsld property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXSLD() {
            return xsld;
        }

        /**
         * Sets the value of the xsld property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXSLD(String value) {
            this.xsld = value;
        }

        /**
         * Gets the value of the xocr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXOCR() {
            return xocr;
        }

        /**
         * Sets the value of the xocr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXOCR(String value) {
            this.xocr = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLatitude(String value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLongitude(String value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the placa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaca() {
            return placa;
        }

        /**
         * Sets the value of the placa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaca(String value) {
            this.placa = value;
        }

        /**
         * Gets the value of the tpSentido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpSentido() {
            return tpSentido;
        }

        /**
         * Sets the value of the tpSentido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpSentido(String value) {
            this.tpSentido = value;
        }

        /**
         * Gets the value of the nsuLeitura property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNSULeitura() {
            return nsuLeitura;
        }

        /**
         * Sets the value of the nsuLeitura property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNSULeitura(String value) {
            this.nsuLeitura = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="chMDFe" type="{http://www.portalfiscal.inf.br/one}TChMDFe"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chMDFe"
    })
    public static class InfMDFe {

        @XmlElement(required = true)
        protected String chMDFe;

        /**
         * Gets the value of the chMDFe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChMDFe() {
            return chMDFe;
        }

        /**
         * Sets the value of the chMDFe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChMDFe(String value) {
            this.chMDFe = value;
        }

    }

}
