//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 02:20:15 PM BRST 
//


package br.com.guava.documento.fiscal.xsd.cte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.centralit.dossie.xsd.sefaz.nacional.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CteConsultaDFe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "cteConsultaDFe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.centralit.dossie.xsd.sefaz.nacional.cte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCTeDFe.ProcCTe }
     * 
     */
    public TCTeDFe.ProcCTe createTCTeDFeProcCTe() {
        return new TCTeDFe.ProcCTe();
    }

    /**
     * Create an instance of {@link TCTeConsultaDFe }
     * 
     */
    public TCTeConsultaDFe createTCTeConsultaDFe() {
        return new TCTeConsultaDFe();
    }

    /**
     * Create an instance of {@link TCTeDFe.ProcCancCTe }
     * 
     */
    public TCTeDFe.ProcCancCTe createTCTeDFeProcCancCTe() {
        return new TCTeDFe.ProcCancCTe();
    }

    /**
     * Create an instance of {@link TCTeDFe.ProcEventoCTe }
     * 
     */
    public ProcEventoCTe createTCTeDFeProcEventoCTe() {
        return new ProcEventoCTe();
    }

    /**
     * Create an instance of {@link TCTeDFe }
     * 
     */
    public TCTeDFe createTCTeDFe() {
        return new TCTeDFe();
    }

    /**
     * Create an instance of {@link TRetCTeConsultaDFe }
     * 
     */
    public TRetCTeConsultaDFe createTRetCTeConsultaDFe() {
        return new TRetCTeConsultaDFe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCTeConsultaDFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "cteConsultaDFe")
    public JAXBElement<TCTeConsultaDFe> createCteConsultaDFe(TCTeConsultaDFe value) {
        return new JAXBElement<TCTeConsultaDFe>(_CteConsultaDFe_QNAME, TCTeConsultaDFe.class, null, value);
    }

}
